name: Bug Report
description: Report a reproducible problem in RSSI Cartographer
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Describe the bug clearly.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Exact steps and command(s) used.
      placeholder: |
        1. Run ...
        2. Open ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: macOS version, Python version, network context.
      placeholder: macOS 15.x, Python 3.x, Wi-Fi AP model...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Output
      description: Paste relevant terminal output or API snippets.
